site_name: Brainwave.jl
theme: readthedocs

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

docs_dir: 'build'

markdown_extensions:
  - extra
  - tables
  - fenced_code

#  - mdx_math
  
pages:
    - Introduction: 'index.md'
    - Function Reference: 'API.md'

